#pragma once

typedef enum {
  RAOS_OK = 0,
  RAOS_E_INVALID_ARG,
  RAOS_E_OUT_OF_RANGE,
  RAOS_E_SIZE_MISMATCH,
  RAOS_E_NOT_CONFIGURED,
  RAOS_E_IK_NO_SOLUTION,
  RAOS_E_TRAJ_FULL,
  RAOS_E_TRAJ_NOT_RUNNING,
  RAOS_E_INTERNAL
} RAOS_Result;